apiVersion: skaffold/v2beta25
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # watch all this yaml files
build:
  local:
    push: false # Do not push to dockerhub 
  artifacts:
    - image: david184/client
      context: client # folder that contains the code for the image
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # Watch for changes in any js file inside src/ If match, copy the file directly into the pod.
          # If doesn't match (example: changing package.json by installing a new library) then rebuild the entire image and update the deployment
          - src: 'src/**/*.js'
            dest: .
    - image: david184/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: david184/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: david184/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: david184/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: david184/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .